name: Run Physics Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.11'
          
      - name: Install Dependencies and Run Tests
        shell: julia --project=Cyclists {0}
        run: |
          using Pkg
          # 1. Installiert alle Abhängigkeiten aus Cyclists/Project.toml
          Pkg.instantiate()
          
          # 2. Führt Testdatei aus
          include("Cyclists/runtests.jl")