name: Run Physics Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.11'
          
      - name: Install Dependencies and Run Tests
        shell: julia --project=Cyclists {0}
        run: |
          using Pkg
          # 1. Liest das Project.toml aus und installiert alle Abhängigkeiten automatisch
          Pkg.instantiate()
          
          # 2. Startet direkt die Tests für das aktuelle Projekt
          Pkg.test()